### ISSUE TITLE
CT: UnivariatePolynomial: x^3 + 10x^2 + 169x failed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/dot#121]
dot is failing unit tests.  This has been occurring on every iteration since CT was restarted on 9/15/23 @ 1:26:30pm.

```
dot : top-level-unit-tests : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1695140008322/dot/dot-tests.html
104 out of 105 tests passed. 1 failed.
UnivariatePolynomial: x^3 + 10x^2 + 169x failed:
first root
at Object.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1695140008322/chipper/dist/js/dot/js/UnivariatePolynomialTests.js:35:10)

UnivariatePolynomial: x^3 + 10x^2 + 169x failed:
second root
at Object.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1695140008322/chipper/dist/js/dot/js/UnivariatePolynomialTests.js:36:10)

[URL] http://128.138.93.172/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1695140008322%2Fdot%2Fdot-tests.html&testInfo=%7B%22test%22%3A%5B%22dot%22%2C%22top-level-unit-tests%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1695140008322%22%2C%22timestamp%22%3A1695140710058%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1695140008322%2Fdot%2Fdot-tests.html&testInfo=%7B%22test%22%3A%5B%22dot%22%2C%22top-level-unit-tests%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1695140008322%22%2C%22timestamp%22%3A1695140710058%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1695140008322/dot/dot-tests.html
[CONSOLE] Failed to load resource: the server responded with a status of 404 (Not Found): http://128.138.93.172/continuous-testing/ct-snapshots/1695140008322/dot/dot-strings_en.json

id: "Sparky Node Puppeteer"
Snapshot from 9/19/2023, 10:13:28 AM
```

**Comment by samreid** [comment]
I'll work on this.

**Comment by samreid** [comment]
The test was failing because of a copy/paste error in the assertions, I corrected it to the actual roots and it is passing locally.  I also fixed a typo in documentation in a related file.  Closing.
