### ISSUE TITLE
Matrix3 pooling is broken

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#74]
Sim errors (dev):
acid-base-solutions
Uncaught Error: Assertion failed: Matrix3 constructor should not be called with any arguments.  Use Matrix3.createFromPool()/Matrix3.identity()/etc.
Error: Assertion failed: Matrix3 constructor should not be called with any arguments.  Use Matrix3.createFromPool()/Matrix3.identity()/etc.
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:22:13)
    at new Matrix3 (http://localhost/dot/js/Matrix3.js?bust=1529500477179:38:15)
    at Function.createFromPool (http://localhost/phet-core/js/ExperimentalPoolable.js?bust=1529500477179:98:20)
    at http://localhost/dot/js/Matrix3.js?bust=1529500477179:987:34
    at Object.execCb (http://localhost/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (http://localhost/sherpa/lib/require-2.1.11.js:866:35)
    at Module. (http://localhost/sherpa/lib/require-2.1.11.js:1113:20)
    at http://localhost/sherpa/lib/require-2.1.11.js:132:17
    at http://localhost/sherpa/lib/require-2.1.11.js:1156:11
    at each (http://localhost/sherpa/lib/require-2.1.11.js:57:23)

![image](https://user-images.githubusercontent.com/679486/41660581-b80c7270-7459-11e8-8724-a14f760f6d57.png)

It looks like CT is fixed after 7:01am, but I'm still seeing this problem in my working copy--and I seem to be all pulled on master, so I'm not sure what is wrong.

**Comment by samreid** [comment]
I'm seeing the same problem on http://phettest.colorado.edu/acid-base-solutions/acid-base-solutions_en.html?ea&brand=phet

Not sure why CT is no longer seeing the problem.

**Comment by samreid** [comment]
This code looks unused:

```js
useDefaultConstruction: true,
```

**Comment by jonathanolson** [comment]
Sorry I believe I had unpushed commits last night. Can you check to see if things are working now?

**Comment by samreid** [comment]
It seems my assertion is still commented out, should we add that back in now?

**Comment by jonathanolson** [comment]
Should be reverted. Can this be closed?

**Comment by samreid** [comment]
All set, thanks!  Closing.
